version: '3'

services:
  ## Database ##
  db:
    image: mysql:latest
    volumes:
      - ./docker/mysql/db_data:/var/lib/mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1" 
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - wp

  ## WordPress ##
  wordpress:
    depends_on:
      - db
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - "${HTTPS_PORT}:443"
      - "${HTTP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./service/wordpress:/var/www/html
      - ./docker/apache:/etc/apache2/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - wp
networks:
  wp:
volumes:
  db_data:
